### ISSUE TITLE
jackstraw sampling

### ISSUE THREAD

**Issue by yulijia** [ncchung/jackstraw#4]
Hi Neo,

I have read the online tutorial and papers for the Jackstraw method, and I am very confused about what is sampled in the jackstraw method.

For PCA, it seems to sample the variables (features) but not the observations (https://cbml.science/post/association-test-with-principal-components/figure/LatentVariableModel.png). But for the clustering, the jackstraw method samples the observations (the cells) but not the variables (the genes) (https://cbml.science/post/test-of-cluster-memberships/figure/jackstraw_cluster_setup.jpg)

From the code of `jackstraw_kmeans` and `jackstraw_pca` it seems both are sampled from the variables (features).

I am not sure if my understanding is correct.
For both PCA and clustering, could you help me understand the sampling process in Jackstraw? Should I sample variables or observations? 

Thanks in advance.

Lijia

**Comment by ncchung** [comment]
Hi Lijia,

> Should I sample variables or observations?

Application of the jackstraw depends on data analysis goals. FYI, whether you create your data matrix such that rows are variables or observations is upto you.

As you may notice, from a programmatic perspective, what is being resampled is some rows (i.e. some % of rows). Those examples are given and explained as the most likely applications for that dataset.

Example for the jackstraw for PCA is a microarray data: In microarray, it is typical that the variables (genes, transcripts, or microarray probes) are the rows, and the observations (samples, etc) are the columns. In most of cases, PCA is applied in this manner so that PCs represent weighted sums of variables. Then, the jackstraw calculates p-values between variables and PCs.

Example for the jackstraw for clustering is a single cell RNA seq: in scRNAseq, it is typical that the rows are the single cells. In practice, people often apply clustering on rows to group single cells into "cell populations". And that's why the jackstraw for clustering, in this example, is applied on single cells.

Let me know this makes sense.

**Comment by yulijia** [comment]
Hi Neo,

Thank for your explanation. 

But I found in your `jackstraw_kmeans` function, it is still sampling from variables. In this case, I will provide a single-cell matrix where the rows represent genes and the columns represent cells as the function input.

https://github.com/ncchung/jackstraw/blob/master/R/jackstraw_kmeans.R#L13
https://github.com/ncchung/jackstraw/blob/master/R/jackstraw_kmeans.R#L116

Is it possible that the function parameter description is incorrect?

**Comment by ncchung** [comment]
You are correct that the function help description is wrong. I need to revise it to be agnostic to semantic meanings of rows/columns.

> @param dat a matrix with \code{m} rows and \code{n} columns.

The R function kmeans() are clustering ``m`` rows into ``k`` clusters. jackstraw_kmeans() work on that same dimension such that it'll calculate ``m`` p-values w.r.t. those clusters.

**Comment by yulijia** [comment]
yep, it makes sense now.
